version: "3.8"
services:
  backend:
    build: ./flask
    container_name: flask_backend
    ports:
      - 5000:5000
    volumes:
      - D:/Lachin/Development/FeaturizationDeployment/featurization-deployment/flask:/flask